version: "3.7"
services:
     app:
        build:
          args:
            user: john
            uid: 1000
          context: ./
          dockerfile: Dockerfile
        image: cozastore
        container_name: cozastore-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
          - ./:/var/www
        networks:
          - cozastore

     db:
         image: mysql:5.7
         container_name: cozastore-db
         restart: unless-stopped
         environment:
           MYSQL_DATABASE: ${DB_DATABASE}
           MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
           MYSQL_PASSWORD: ${DB_PASSWORD}
           MYSQL_USER: ${DB_USERNAME}
           SERVICE_TAGS: dev
           SERVICE_NAME: mysql
         volumes:
           - ./docker-compose/mysql:/docker-entrypoint-initdb.d
         networks:
           - cozastore

     nginx:
         image: nginx:1.17-alpine
         container_name: cozastore-nginx
         restart: unless-stopped
         ports:
           - 8080:80
         volumes:
           - ./:/var/www
           - ./docker-compose/nginx:/etc/nginx/conf.d
         networks:
           - cozastore



networks:
  cozastore:
    driver: bridge
